version: '3'

services:
  web-app:
    build: .
    ports:
      - '8009:8009'
    volumes:
      - .:/project
    command: >
      sh -c "cd backend &&
             gunicorn tinder_serv.wsgi:application --bind 0.0.0.0:8009"
    environment:
      TZ: Europe/Moscow
