# Generated by Django 4.2.13 on 2024-11-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_test_question_answeroption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
        migrations.AlterField(
            model_name='item',
            name='cost',
            field=models.FloatField(default=0),
        ),
    ]
